name: Pylint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: |
        make
        pip install pylint
        pylint docsis_exporter.py
